/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

#include <iostream>

int main(){
    uint64_t sum=0;
    uint64_t lim=4000000;
    uint64_t a=2;
    uint64_t b=1;
    
    while(a<lim && b<lim){
        b+=a;
        if(b%2==0){ sum+=b;}
        a+=b;
        if(a%2==0){ sum+=a;}

    }
    std::cout<<sum<<"\n";
    
}
  
  
